# Generated by Django 2.0rc1 on 2018-01-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets_example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='style',
        ),
    ]
