# Generated by Django 2.0rc1 on 2018-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets_example', '0002_auto_20180116_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='file',
            field=models.FileField(blank=True, max_length=2000, upload_to=''),
        ),
    ]
