# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets_example', '0003_auto_20171127_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
