# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets_example', '0005_auto_20171127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='file',
            field=models.FileField(max_length=2000, upload_to=''),
        ),
    ]
